version: '3'
services:
  tomcat:
    image: tomcat
    container_name: tomcat
    restart: on-failure
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    networks:
      - week2

  database:
    image: mysql:8.0.31
    container_name: week2
    restart: always
    ports:
      - "3310:3306"
    environment:
      MYSQL_USER: mptimchenko
      MYSQL_PASSWORD: 12341990
      MYSQL_DATABASE: aston_rest
      MYSQL_ROOT_PASSWORD: root
    networks:
      - week2

networks:
  week2:
    driver: bridge